In [4]:
import numpy as np
import pandas as pd

In [6]:
#creating data frame
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)#change row 0,1 in the array name 
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [60]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [61]:
#select colume
df2[["Name","City"]]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [8]:
#creating column
df2["Desgination"]=["doctor","eng","doctor","eng"]

In [63]:
df2

    Name  Age      City  Salary Desgination
0   John   28  New York   65000      doctor
1   Anna   34     Paris   70000         eng
2  Peter   29    Berlin   62000      doctor
3  Linda   42    London   85000         eng

In [16]:
#removing column in name , axis 1 for vatical
df2.drop("Desgination" ,axis=1,inplace=True)

KeyError: "['Desgination'] not found in axis"

In [14]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [66]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [67]:
#removing row no 0 , axis 0 for horizontal 
df2.drop(0,axis=0)

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [74]:
#selecting rows
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [76]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [78]:
#selecting subsets of rows and columns
df2.loc[[0,1],["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [79]:
df2.loc[[2,3],["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [87]:
#conditional selection
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [88]:
# i only to see  thos pepole whose age is sbove 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [91]:
# i only to see  thos pepole whose age is sbove 30 and there city must be paris
df2[(df2["Age"]>30) & (df2["City"] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000